-- 05_Inserta_Libros.sql
USE Biblioteca;

INSERT INTO Libros (titulo, autor, fecha_edicion) VALUES
('Niebla', 'Miguel de Unamuno', 1914),
('El árbol de la ciencia', 'Pío Baroja', 1911),
('San Manuel Bueno, mártir', 'Miguel de Unamuno', 1931),
('Campos de Castilla', 'Antonio Machado', 1912),
('La voluntad', 'Azorín', 1902),
('Camino de perfección (pasión mística)', 'Pío Baroja', 1902),
('Soledades. Galerías. Otros poemas', 'Antonio Machado', 1907),
('Antonio Azorín', 'Azorín', 1903),
('Abel Sánchez', 'Miguel de Unamuno', 1917),
('La busca', 'Pío Baroja', 1904),
('Juan de Mairena', 'Antonio Machado', 1936),
('Las confesiones de un pequeño filósofo', 'Azorín', 1904),
('Zalacaín el aventurero', 'Pío Baroja', 1908),
('Defensa de la hispanidad', 'Ramiro de Maeztu', 1934),
('La ruta de Don Quijote', 'Azorín', 1905),
('Amor y pedagogía', 'Miguel de Unamuno', 1902),
('Aurora roja', 'Pío Baroja', 1904),
('Poesías completas', 'Antonio Machado', 1908),
('Los pueblos', 'Azorín', 1905),
('El Intransigente', 'Pío Baroja', 1907),
('El sentimiento trágico de la vida', 'Miguel de Unamuno', 1913),
('La feria de los discretos', 'Pío Baroja', 1905),
('Tierras de España', 'Azorín', 1903),
('Luces de Bohemia', 'Ramón del Valle-Inclán', 1924),
('Sonata de otoño', 'Ramón del Valle-Inclán', 1902),
('Sonata de estío', 'Ramón del Valle-Inclán', 1903),
('Sonata de primavera', 'Ramón del Valle-Inclán', 1904),
('Sonata de invierno', 'Ramón del Valle-Inclán', 1905),
('La lámpara maravillosa', 'Ramón del Valle-Inclán', 1916),
('Divinas palabras', 'Ramón del Valle-Inclán', 1919),
('Tirano Banderas', 'Ramón del Valle-Inclán', 1926),
('Águila de blasón', 'Ramón del Valle-Inclán', 1907),
('Romance de lobos', 'Ramón del Valle-Inclán', 1907),
('Comedias bárbaras (trilogía)', 'Ramón del Valle-Inclán', 1915),
('Los intereses creados', 'Jacinto Benavente', 1907),
('Señora Ama', 'Jacinto Benavente', 1908),
('Rosas de otoño', 'Jacinto Benavente', 1905),
('El mal que hacen los buenos', 'Jacinto Benavente', 1905),
('La ciudad de la niebla', 'Pío Baroja', 1909),
('Los trabajos del infatigable creador Pío Cid', 'Miguel de Unamuno', 1921),
('Mala hierba', 'Pío Baroja', 1904),
('Alma española (Ensayos)', 'Miguel de Unamuno', 1902),
('La casa de Aizgorri', 'Pío Baroja', 1900),
('La leyenda del Cid Campeador', 'Ramón Menéndez Pidal', 1929),
('El caballero Audaz', 'Pío Baroja', 1912),
('Por tierras de Portugal y España', 'Miguel de Unamuno', 1911),
('César o nada', 'Pío Baroja', 1910),
('Mi religión y otros ensayos filosóficos', 'Miguel de Unamuno', 1910),
('Sangre española', 'Pío Baroja', 1906),
('España invertebrada', 'José Ortega y Gasset', 1921),
('La agonía del cristianismo', 'Miguel de Unamuno', 1925),
('Andanzas y visiones españolas', 'Miguel de Unamuno', 1922),
('Las inquietudes de Shanti Andía', 'Pío Baroja', 1911),
('Teresa', 'Azorín', 1907),
('El aprendiz de conspirador', 'Pío Baroja', 1901),
('Castilla', 'Azorín', 1912),
('Paradox, rey', 'Pío Baroja', 1906),
('La pena capital', 'Pío Baroja', 1900),
('Troteras y danzaderas', 'Ramón del Valle-Inclán', 1913),
('El marqués de Bradomín (serie)', 'Ramón del Valle-Inclán', 1907),
('Flor de santidad', 'Ramón del Valle-Inclán', 1904),
('La guerra carlista (trilogía)', 'Pío Baroja', 1908),
('El mayorazgo de Labraz', 'Pío Baroja', 1903),
('Nuevo Mundo (poemas)', 'Antonio Machado', 1920),
('Últimas poesías', 'Antonio Machado', 1940),
('Diario de un poeta recién casado', 'Juan Ramón Jiménez', 1917),
('Platero y yo', 'Juan Ramón Jiménez', 1917),
('Elegías', 'Miguel de Unamuno', 1907),
('Rimas', 'Antonio Machado', 1920),
('Nieblas de mi alma', 'Miguel de Unamuno', 1916),
('Cancionero', 'Antonio Machado', 1924),
('Teresa (reedición)', 'Azorín', 1907),
('Los últimos románticos', 'Azorín', 1906),
('España y los españoles', 'Miguel de Unamuno', 1921),
('El paisaje de España', 'Azorín', 1917),
('El libro de Ruth', 'Pío Baroja', 1916),
('La leyenda de Jaun de Alzate', 'Pío Baroja', 1922),
('Las ciudades', 'Azorín', 1922),
('Desde el mirador', 'Azorín', 1907),
('El alma castellana', 'Azorín', 1900),
('Hacia otra España', 'Miguel de Unamuno', 1902),
('La raza', 'Miguel de Unamuno', 1901),
('En tierra de nadie', 'Pío Baroja', 1907),
('La caverna del duende', 'Pío Baroja', 1919),
('El hotel del cisne', 'Pío Baroja', 1905),
('La dama errante', 'Pío Baroja', 1908),
('La estrella del capitán Chimista', 'Pío Baroja', 1909);
GO